<?php
namespace PHPSocketIO\Response;
use PHPSocketIO\Http\WebSocket\Frame;

/**
 * Test class for Request.
 * Generated by PHPUnit on 2013-05-30 at 13:37:50.
 */
class ResponseWebSocketFrameTest extends \PHPUnit_Framework_TestCase
{

    public function test__to_string()
    {
        $response = new ResponseWebSocketFrame(Frame::generate('test'));
        $this->assertNotEmpty($response);
    }

}