<?php
namespace PHPSocketIO\Response;

/**
 * Test class for Request.
 * Generated by PHPUnit on 2013-05-30 at 13:37:50.
 */
class ResponseRawTest extends \PHPUnit_Framework_TestCase
{
    
    public function test__toString()
    {
        $content = md5(rand().  microtime());
        $response = new ResponseRaw($content);
        $output = $response->__toString();
        $this->assertEquals($content, $output);
    }

}