<?php
namespace PHPSocketIO\Response;

/**
 * Test class for Request.
 * Generated by PHPUnit on 2013-05-30 at 13:37:50.
 */
class ResponseChunkStartTest extends \PHPUnit_Framework_TestCase
{
    public function test__toString()
    {
        $content = md5(rand().  microtime());
        $response = new ResponseChunkStart($content);
        $output = $response->__toString();
        $this->assertTrue(preg_match('/Transfer-Encoding:\s*chunked/i', $output) != 0 , "has Chunk header");
        list(, $chunkContent) = explode("\r\n\r\n", $output);
        $this->assertEquals(sprintf("%x\r\n%s\r\n", strlen($content), $content), $chunkContent);
    }
}