<?php
namespace PHPSocketIO\Event;
use PHPSocketIO\Request\Request;

/**
 * Test class for Request.
 * Generated by PHPUnit on 2013-05-30 at 13:37:50.
 */
class RequestEventTest extends \PHPUnit_Framework_TestCase
{

    public function test_setRequest()
    {
        $requestEvent = new RequestEvent();
        $this->assertTrue($requestEvent->setRequest(new Request()));
    }

    public function test_getRequest()
    {
        $request = new Request();
        $requestEvent = new RequestEvent();
        $requestEvent->setRequest($request);
        $this->assertEquals($request, $requestEvent->getRequest());
    }
}
